# Generated by Django 5.2.16 on 2026-07-10 16:48

# State-only: 0.2.0 moved the BaseModel.id default from uuid.uuid4 to
# _make_uuid (ICV_CORE_UUID_VERSION). Defaults are Python-side, so this
# emits no SQL; it only realigns migration state so makemigrations
# --check stays clean.

from django.db import migrations, models

import icv_core.models.base


class Migration(migrations.Migration):
    dependencies = [
        ("icv_core", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="adminactivitylog",
            name="id",
            field=models.UUIDField(
                default=icv_core.models.base._make_uuid,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="auditentry",
            name="id",
            field=models.UUIDField(
                default=icv_core.models.base._make_uuid,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
        migrations.AlterField(
            model_name="systemalert",
            name="id",
            field=models.UUIDField(
                default=icv_core.models.base._make_uuid,
                editable=False,
                primary_key=True,
                serialize=False,
                verbose_name="ID",
            ),
        ),
    ]
